### ISSUE TITLE
Problem with bash word splitting parameters of no value in double quotes

### ISSUE THREAD

**Issue by johnwarburton** [MartyEwings/agent_run_with_tags#2]
Hi @MartyEwings 

Thanks for this task. As you note, it definitely fills a gap that I would have thought would be there from day 1

I just installed your task and gave it a run of one tag and came up with this error:
```
Error: Could not prepare for execution: The puppet agent command does not take parameters
```
It is happening because parameters with no values expanded within double quotes become a null argument and is passed as an empty string ''. See https://www.gnu.org/software/bash/manual/html_node/Word-Splitting.html

> If a parameter with no value is expanded within double quotes, a null argument results and is retained and passed to a command as an empty string. 

You can see when I pass double quotes to ls and then the script running:
```
# ls ""
ls: cannot access '': No such file or directory
# export PT_tag1=tag1
# ./agent_run_tags.sh 
+ puppet agent -t '' '' --tags tag1 ''
Error: Could not prepare for execution: The puppet agent command does not take parameters
```

There are a number of ways to fix this. referencing
https://unix.stackexchange.com/questions/388475/why-do-options-in-a-quoted-variable-fail-but-work-when-unquoted/388572#388572
https://unix.stackexchange.com/questions/415990/how-can-i-expand-a-quoted-variable-to-nothing-if-its-empty

1. Remove the double quotes from the variables and wrap them variables in braces
```puppet agent -t ${PT_param1} ${PT_param2}  --tags ${PT_tag1} ${PT_tag2}```
2. Using arrays to hold variables and expand that way
```declare -a PT_params=(${PT_param1} ${PT_param2})
declare -a PT_tags=(${PT_tag1} ${PT_tag2})
puppet agent -t ${PT_params[@]}  --tags ${PT_tags[@]}
```
Which brings me to my next point, according to https://puppet.com/docs/puppet/6.4/lang_tags.html#using-tags the tags "should be a comma-separated list of tags, with no spaces between tags"

So, either remove the restriction of only 2 tags - as the first string can be as long as you want with comma separated no spaces of all the tags you want, or join the tags array:
```TAGS=$(IFS=,; echo "${PT_tags[*]}")
puppet agent -t ${PT_params[@]}  --tags ${TAGS}
```

I've tested these ideas with a quick fork at https://github.com/johnwarburton/agent_run_with_tags and it works as expected

Do you want me to formalise this a bit more and do a proper fork and pull request?

Thanks

John

**Comment by MartyEwings** [comment]
Sure! Go right ahead, thanks for the input

**Comment by johnwarburton** [comment]
Thanks @MartyEwings

**Comment by johnwarburton** [comment]
Hi @MartyEwings 
Please see PR #3 - now passes all tests...

Regards
John

**Comment by MartyEwings** [comment]
Closed with PR3
